config/routes.rb
Rails.application.routes.draw do
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'ideas#index'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  resources :ideas do 

    resources :likes, shallow: true, only: [:create, :destroy]

    resources :reviews, shallow: true, only: [:create, :destroy]

  end

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action :create, :read, :update, :destroy, to: :crud

    can(:crud, Idea) do |idea| 
      idea.user == user 
    end


    can(:crud, Review) do |review|
      review.user == user 
    end 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord

    
    has_many :likes
    has_many :likers, through: :likes, source: :user


    belongs_to :user

    has_many(:reviews, dependent: :destroy)
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :idea
end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :idea

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    validates(:email, presence: true, uniqueness: true, format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i)

    has_secure_password

    ###############

    has_many :likes
    has_many :liked_ideas, through: :likes, source: :idea

    #########################
    
    has_many :ideas
    has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private

  
  def current_user
    if session[:user_id].present?
      @current_user ||= User.find session[:user_id] 
    end
  end

  helper_method :current_user
  

  def user_signed_in?
    current_user.present?
  end
  helper_method :user_signed_in?


  def authenticate_user!
    unless user_signed_in?
      flash[:danger] = "You need to be signed in first!"
      redirect_to new_session_path
    end
  end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

    before_action :authenticate_user!, except: [:index, :show]

    before_action :authorize!, only: [:edit, :update, :destroy]

    def new 

        @idea = Idea.new

    end

    def create 
        idea_params = params.require(:idea).permit(:title, :description)
        @idea = Idea.new idea_params
        @idea.user = current_user
        if @idea.save 
            redirect_to @idea
        else
            render :new 
        end
    end
    ####################

    def edit 
        @idea = Idea.find params[:id]
    end

    def update
        idea_params = params.require(:idea).permit(:title, :description)
        @idea = Idea.find params[:id]
        if @idea.update idea_params
            redirect_to @idea
        else
            render :edit
        end
    end
    ####################

    def show

            @idea = Idea.find params[:id]
            @review = Review.new
            @reviews = @idea.reviews.order(created_at: :DESC)
            @like = @idea.likes.find_by(user: current_user)
        
    end
    ####################

    def index
        @idea = Idea.order(created_at: :DESC)
    end
    ####################

    def destroy
        @idea = Idea.find(params[:id])
        @idea.destroy
        redirect_to ideas_path
    end
    
    def authorize! 
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, Idea)
    end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
    
        idea = Idea.find params[:idea_id]
        like = Like.new(idea: idea, user: current_user)
    
        
        if like.save
          flash[:success] = "Idea Liked"
        else
          flash[:danger] = like.errors.full_messages.join(", ")
        end
        redirect_to idea_path(idea)
      end
    
      def destroy
        like = current_user.likes.find params[:id] 
        if like.destroy
          flash[:success] = "Idea Unliked"
        else
          flash[:warning] = "It's rude to unlike something you've already liked"
        end
    
        redirect_to idea_path(like.idea)
      end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def create 
        @idea = Idea.find(params[:idea_id])
        @review = Review.new review_params
        @review.idea = @idea 
        @review.user = current_user
        if @review.save 
            redirect_to @idea
        else 
            @reviews = @idea.reviews.order(created_at: :desc)
            render 'ideas/show'
        end
    end

    #########################

    def destroy
        @review = Review.find params[:id]
        if can?(:crud, @review)
            @review.destroy 
            redirect_to @review.idea
        else 
            
            head :unauthorized
        end
        
    end

    #############################
    private 

    def review_params 
        params.require(:review).permit(:body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  
  def create
    user = User.find_by_email params[:email]

    if user&.authenticate params[:password]

      session[:user_id] = user.id
      
      flash[:success] = "User Logged In"


      redirect_to ideas_path
    else
      flash[:warning] = "Couldn't log In"
      
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to ideas_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
       
    end

    def create
        @user = User.new params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
        if @user.save
          flash.delete(:warning)
          redirect_to ideas_path
        else
          flash[:warning] = "unable to create user"
          render :new
        end
        
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/ideas/_form.html.erb
<% if @idea.errors.any? %>
    <ul>
        <% @idea.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= form_for @idea do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary btn-lg' %>

<% end %>

app/views/ideas/edit.html.erb
<h1>Edit Idea</h1>

<%= render 'form' %>

app/views/ideas/index.html.erb
 <div class="d-flex align-content-stretch flex-wrap">
<% @idea.each do |idea| %>
        <div class="list-group-item p-2 m-2" style="min-width: 350px; width: 31%; max-width: 95vw; word-wrap: break-word;"><%= link_to idea.title, idea_path(idea) %><p class="card-text"><%= idea.description %></p></div>
<% end %>
    </div>

app/views/ideas/new.html.erb
<h1>Add a new Idea</h1>

<%= render 'form' %>

app/views/ideas/show.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><%= @idea.title %></h5>
    <p class='text-muted'><%= @idea.user.first_name %> <%= @idea.user.last_name %></p>
    
        <p class="card-text"> <%= @idea.description %></p>

         <small>Liked by: <%= @idea.likes.count %></small>
  <small>
    <% if @like.present? %>
      <%= link_to(
          "Unlike",
          like_path(@like),
          method: :delete
        )
      %>
    <% else %>
      <%= link_to(
          "Like",
          idea_likes_path(@idea),
          method: :post
        )
      %>
    <% end %>
  </small>
     
    <% if can? :crud, @idea %>
        <%= link_to "Edit idea", edit_idea_path(@idea), class: "btn btn-primary" %>
        <%= link_to 'Delete idea', 
            idea_path(@idea), 
            class: "btn btn-danger",
            method: :delete, 
            data: { confirm: 'Are you sure that you want to delete this post? '} 
        %>
      </div>
    <% end %>
</div>


<hr />
<%= form_for [@idea, @review] do |f| %>
  <div class="card-body">
    <h4>Add a Review</h4>

    <% if @review.errors.present? %>
        <p>
            <%= @review.errors.full_messages.join(', ') %>
        </p>
    <% end %>

    <div class="form-group">
        <%= f.label :body, class: "d-none" %>
        <%= f.text_area :body, class: "form-control" %>
    </div>
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>

<% end %>

<hr />


<% @reviews.each do |review| %>
  <div class="card-body">
    <h4>Reviews</h4>
   
    <ul class="list-group">
        <li class="list-group-item">
            <p><%= review.body %></p>
    
          Reviewed <%= time_ago_in_words(review.created_at) %> By <%= review.user.first_name %> <%= review.user.last_name %>
        </small>
        

           <% if can? :crud, review %>
                <%= link_to 'Delete',
                    review_path(review),
                    class: "btn btn-danger brn-sm",
                    method: :delete, 
                    data: {
                        confirm: 'Are you sure that you want to delete this comment?'
                    }
                %>
            <% end %>
        </li>
    </ul>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav class='navbar navbar-light bg-light mb-5'>
    <a class="nav-link" href="/">
          <img
          class="images" 
          src="/assets/images/imag.png"
          height="70px"
          alt="imag"
        /></a>

      <span class='navbar-brand mb-0 h1'>Idea Factory</span>
      <ul style="float: right;">
        <%= link_to 'Home', root_path, class: 'btn' %>
        
        <%= link_to 'Create User', new_user_path, class: 'btn'%>
   
        <div>
       <% if user_signed_in? %>
      <%= link_to "Sign out", session_path, method: :delete, class: 'btn btn-danger' %>
      <%= current_user.first_name %> <%= current_user.last_name %>
       <%= link_to 'New Idea', new_idea_path, class: 'btn'%>
       <% else %>
      <%= link_to "Sign In", new_session_path, class: 'btn btn-success'%>
      <% end %>

        </div>
      </ul>
    </nav>






   <% flash.each do |type, message| %>
        <div class='bg-<%= type %> p-1 rounded mb-3 shadow-sm'>
          <%= message %>
        </div>
      <% end %>


    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create User</h1>
<% if @user.errors.present? %>
  <p>
    <%= @user.errors.full_messages.join(', ')%>
  </p>
<% end %>
<div class='shadow-sm p-3 mb-5 bg-white rounded'>
  <%= form_with model: @user, local: true do |f| %>
    <div class='form-group'>
      <%= f.label :first_name%>
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :last_name%>
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :email%>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password%>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit "Create User", class: 'btn btn-primary' %>
  <% end %>
</div>